apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logindep
  name: perceptiview-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logindep
  template:
    metadata:
      labels:
        app: logindep
    spec:
      containers:
      - image: registry.gitlab.com/ez-machine-learning/perceptiview:ce509772
        name: perceptiview-c
