apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perceptiview
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: perceptiview
            port:
              number: 80

