apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.secrets.registryaccess.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.secrets.registryaccess.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson

