apiVersion: v1
kind: Service
metadata:
  name: perceptiview
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.label }}

